const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const THEME='alureal-ui-theme';const storageGet=k=>{try{return localStorage.getItem(k)}catch{return null}};const storageSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};const index=[['Visão geral','index.html'],['Foundations','foundations.html'],['Tokens','tokens.html'],['Componentes','components.html'],['Padrões','patterns.html'],['Acessibilidade','accessibility.html'],['Playground','playground.html'],['Changelog','changelog.html']];
function theme(v){const next=v==='light'?'light':'dark';document.documentElement.dataset.theme=next;storageSet(THEME,next);$$('[data-theme-toggle]').forEach(b=>{b.textContent=next==='light'?'☾':'☀';b.setAttribute('aria-label',next==='dark'?'Ativar modo claro':'Ativar modo escuro')})}
function shell(){const s=$('[data-docs-shell]');if(!s)return;const fallback=s.innerHTML;s.innerHTML='<aside class="sidebar"><div class="logo">alu<b>real</b> UI</div><button class="search-trigger" data-search-open>⌕ Buscar documentação</button><div class="nav-section">Começar</div><nav class="nav"><a href="index.html">Visão geral</a><a href="foundations.html">Foundations</a><a href="tokens.html">Tokens</a></nav><div class="nav-section">Construir</div><nav class="nav"><a href="components.html">Componentes</a><a href="patterns.html">Padrões</a><a href="accessibility.html">Acessibilidade</a><a href="playground.html">Playground</a></nav><div class="nav-section">Projeto</div><nav class="nav"><a href="changelog.html">Changelog</a></nav><div class="side-footer"><button class="icon-btn" data-theme-toggle aria-label="Ativar modo claro">☀</button><a class="button" href="https://github.com/allfariaclaro/alureal-ui-kit">GitHub</a></div></aside><main class="main" data-main></main><nav class="mobile-nav"><a href="index.html">⌂<span>Início</span></a><a href="components.html">□<span>Componentes</span></a><a href="playground.html">◌<span>Playground</span></a><a href="changelog.html">↻<span>Changelog</span></a></nav><div class="search-overlay" data-search-overlay><div class="search-modal"><input autofocus data-search-input placeholder="Buscar tokens, componentes, padrões..."><div class="search-results" data-search-results></div></div></div>'}
function initTheme(){const raw=storageGet(THEME);const stored=raw==='dark'||raw==='light'?raw:null;let system='dark';try{system=window.matchMedia?.('(prefers-color-scheme: light)').matches?'light':'dark'}catch{}theme(stored||system);if(!document.documentElement.dataset.themeBound){document.addEventListener('click',e=>{const b=e.target instanceof Element?e.target.closest('[data-theme-toggle]'):null;if(!b)return;theme(document.documentElement.dataset.theme==='dark'?'light':'dark')});document.documentElement.dataset.themeBound='1'}}
function head(title,sub,badge='Docs'){const light=document.documentElement.dataset.theme==='light';return '<div class="topbar"><span class="breadcrumb">Alureal UI / '+title+'</span><div><button class="icon-btn" data-search-open>⌕</button> <button class="icon-btn" data-theme-toggle aria-label="'+(light?'Ativar modo escuro':'Ativar modo claro')+'">'+(light?'☾':'☀')+'</button></div></div><header class="main-head"><span class="badge">'+badge+'</span><h1>'+title+'</h1><p>'+sub+'</p></header>'}
function overview(){const m=$('[data-main]');m.innerHTML=head('Design system','Infraestrutura reutilizável para interfaces Alureal.','v0.2')+'<section class="stats"><article class="stat"><strong>18</strong><span>tokens base</span></article><article class="stat"><strong>12</strong><span>componentes</span></article><article class="stat"><strong>6</strong><span>padrões</span></article><article class="stat"><strong>AA</strong><span>meta de contraste</span></article></section><section class="section"><div class="section-head"><div><h2>Comece pela fundação</h2><p>Entenda as regras antes de copiar componentes.</p></div></div><div class="card-grid"><a class="card" href="foundations.html"><span class="badge">01</span><h3>Foundations</h3><p>Princípios, tipografia, grid e espaçamento.</p></a><a class="card" href="tokens.html"><span class="badge">02</span><h3>Tokens</h3><p>Cores, radius, sombra e movimento.</p></a><a class="card" href="components.html"><span class="badge">03</span><h3>Componentes</h3><p>Botões, inputs, cards, modais e estados.</p></a></div></section><section class="section"><div class="section-head"><div><h2>Fluxo recomendado</h2></div></div><div class="pattern-list"><article class="pattern"><strong>1 · Token</strong><span>Escolha a linguagem visual centralizada.</span></article><article class="pattern"><strong>2 · Componente</strong><span>Construa uma unidade previsível.</span></article><article class="pattern"><strong>3 · Padrão</strong><span>Combine componentes em uma tarefa real.</span></article><article class="pattern"><strong>4 · QA</strong><span>Cheque responsividade, foco e movimento.</span></article></div></section>'}
function foundations(){const m=$('[data-main]');m.innerHTML=head('Foundations','Princípios que mantêm consistência sem deixar todos os produtos iguais.')+'<section class="card-grid"><article class="card"><h3>Clareza</h3><p>Hierarquia antes de decoração.</p></article><article class="card"><h3>Responsividade</h3><p>Mobile é condição de projeto, não etapa final.</p></article><article class="card"><h3>Motion</h3><p>Animação explica mudança e hierarquia.</p></article></section><section class="section"><div class="section-head"><div><h2>Escala de espaçamento</h2></div></div><div class="token-table">'+[4,8,12,16,24,32,48,80].map(v=>'<div class="token-row"><strong>'+v+' px</strong><span>--space-'+v+'</span><span style="width:'+Math.min(100,v*2)+'px;height:10px;background:var(--brand);border-radius:99px"></span></div>').join('')+'</div></section>'}
function tokens(){const m=$('[data-main]');m.innerHTML=head('Tokens','Decisões visuais centralizadas para reduzir inconsistência.')+'<section class="swatches"><article class="swatch"><div class="swatch-color" style="background:#080b10"></div><div class="swatch-meta"><strong>Background</strong><br><small>--bg</small></div></article><article class="swatch"><div class="swatch-color" style="background:#10151e"></div><div class="swatch-meta"><strong>Surface</strong><br><small>--surface</small></div></article><article class="swatch"><div class="swatch-color" style="background:#d7b56d"></div><div class="swatch-meta"><strong>Brand</strong><br><small>--brand</small></div></article><article class="swatch"><div class="swatch-color" style="background:#67c587"></div><div class="swatch-meta"><strong>Success</strong><br><small>--success</small></div></article></section><section class="section"><div class="token-table"><div class="token-row header"><span>Token</span><span>Uso</span><span>Valor base</span></div>'+[['--radius-sm','Inputs compactos','10px'],['--radius-md','Cards','18px'],['--radius-lg','Surfaces principais','28px'],['--fast','Hover','160ms'],['--normal','Transições','280ms']].map(r=>'<div class="token-row"><strong>'+r[0]+'</strong><span>'+r[1]+'</span><span>'+r[2]+'</span></div>').join('')+'</div></section>'}
function components(){const m=$('[data-main]');m.innerHTML=head('Componentes','Peças pequenas, previsíveis e combináveis.')+'<section class="component-grid"><article class="component"><h3>Button</h3><div class="preview"><button class="demo-button">Ação principal</button></div><div class="code"><button class="copy" data-copy>Copiar</button><pre>&lt;button class="button primary"&gt;Ação&lt;/button&gt;</pre></div></article><article class="component"><h3>Input</h3><div class="preview"><input class="demo-input" placeholder="Seu nome"></div><div class="code"><button class="copy" data-copy>Copiar</button><pre>&lt;input class="input" /&gt;</pre></div></article><article class="component"><h3>Card</h3><div class="preview"><div class="card" style="width:min(280px,100%)"><span class="badge">Produto</span><h3>Dashboard</h3><p>Superfície reutilizável.</p></div></div></article><article class="component"><h3>Badge</h3><div class="preview"><span class="badge">Disponível</span></div></article></section>';bindCopy()}
function patterns(){const m=$('[data-main]');m.innerHTML=head('Padrões','Composições recorrentes para tarefas reais.')+'<div class="pattern-list">'+[['Hero de conversão','Mensagem → prova → CTA principal.'],['Formulário progressivo','Perguntar apenas o necessário para avançar.'],['Dashboard operacional','Resumo → exceção → ação.'],['Confirmação destrutiva','Explicar consequência e facilitar cancelamento.'],['Empty state','Explicar o vazio e oferecer próximo passo.'],['Mobile navigation','Poucas ações principais sempre acessíveis.']].map(x=>'<article class="pattern"><strong>'+x[0]+'</strong><span>'+x[1]+'</span></article>').join('')+'</div>'}
function accessibility(){const m=$('[data-main]');m.innerHTML=head('Acessibilidade','Comportamentos padrão, não checklist final.')+[['Foco visível','Todo elemento interativo mostra onde o teclado está.'],['Contraste','Texto e estado não dependem de tons muito próximos.'],['Reduced motion','Movimento respeita preferência do sistema.'],['Touch targets','Controles principais mantêm área confortável.'],['Semântica','Links, botões e headings mantêm papéis corretos.']].map(x=>'<article class="a11y"><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join('')}
function playground(){const m=$('[data-main]');m.innerHTML=head('Playground','Ajuste parâmetros e veja a composição responder.','Interactive')+'<section class="playground"><aside class="controls"><label>Radius<input type="range" min="4" max="36" value="18" data-radius></label><label>Escala<input type="range" min=".85" max="1.08" step=".01" value="1" data-scale></label><label>Tema<select data-play-theme><option>Surface</option><option>Brand</option></select></label></aside><div class="play-preview"><article class="play-card" data-play-card><span class="badge">Preview</span><h2>Card ajustável</h2><p class="muted">Tokens podem alimentar ferramentas internas e documentação viva.</p><button class="demo-button">Ação</button></article></div></section>';const r=$('[data-radius]'),s=$('[data-scale]'),c=$('[data-play-card]');const update=()=>{c.style.setProperty('--radius-demo',r.value+'px');c.style.setProperty('--scale-demo',s.value)};r.oninput=s.oninput=update;update()}
function changelog(){const m=$('[data-main]');m.innerHTML=head('Changelog','Evolução do sistema e decisões relevantes.')+'<section class="changelog"><article class="release"><time>v0.2</time><div><h3>Documentação navegável</h3><p class="muted">Busca, playground, foundations e estrutura completa.</p></div></article><article class="release"><time>v0.1</time><div><h3>Base inicial</h3><p class="muted">Tokens, botões, cards, formulários, modal e toast.</p></div></article></section>'}
function bindCopy(){$$('[data-copy]').forEach(b=>b.onclick=async()=>{const text=b.parentElement.querySelector('pre').textContent;await navigator.clipboard?.writeText(text);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar',1200)})}
function search(){$$('[data-search-open]').forEach(b=>b.onclick=()=>{$('[data-search-overlay]').classList.add('open');setTimeout(()=>$('[data-search-input]').focus(),50)});$('[data-search-overlay]')?.addEventListener('click',e=>{if(e.target.matches('[data-search-overlay]'))e.currentTarget.classList.remove('open')});const input=$('[data-search-input]');if(input)input.oninput=()=>{const q=input.value.toLowerCase();$('[data-search-results]').innerHTML=index.filter(x=>x[0].toLowerCase().includes(q)).map(x=>'<a class="result" href="'+x[1]+'"><strong>'+x[0]+'</strong><br><small>Alureal UI</small></a>').join('')}}
function renderRoute(){
  const p=location.pathname.split('/').pop()||'index.html';
  if(p==='index.html'||p==='')overview();
  else if(p==='foundations.html')foundations();
  else if(p==='tokens.html')tokens();
  else if(p==='components.html')components();
  else if(p==='patterns.html')patterns();
  else if(p==='accessibility.html')accessibility();
  else if(p==='playground.html')playground();
  else if(p==='changelog.html')changelog();
}
const safeRun=(name,fn)=>{try{fn()}catch(error){console.error('[ALUREAL UI] '+name+' failed',error);const main=$('[data-main]');if(main&&!main.textContent.trim())main.innerHTML='<section class="card"><h1>Alureal UI</h1><p>A documentação principal continua disponível pela navegação.</p></section>'}};
function init(){safeRun('shell',shell);safeRun('theme',initTheme);safeRun('route',renderRoute);safeRun('search',search)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();